// src/lib/mockData.ts
import type {
  WhatsAppContact,
  WhatsAppConversation,
  WhatsAppMessage,
  Template,
  Campaign,
  ChatbotFlow,
  FlowStep,
  Tag,
  CrmUser,
  ConversationNote,
} from '@/types';

// ----- Contacts -----
export const MOCK_CONTACTS: any = [
  {
    id: 'c1',
    name: 'Rahul Sharma',
    phone: '+91 98765 43210',
    stage: 'Qualified',
    email: 'rahul@email.com',
    preferred_location: 'Wakad, Pune',
    budget_min: 5000000,
    budget_max: 8000000,
    property_type: 'Apartment',
    source: 'WhatsApp',
    assigned_to: 'u1',
    notes: 'Interested in 2BHK',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    tags: [
      { id: 't1', name: 'Hot Lead', color: '#EF4444' },
      { id: 't2', name: 'Buyer', color: '#3B82F6' },
    ],
  },
  {
    id: 'c2',
    name: 'Priya Mehta',
    phone: '+91 87654 32109',
    stage: 'New',
    email: 'priya@email.com',
    preferred_location: 'Baner, Pune',
    budget_min: 3000000,
    budget_max: 5000000,
    property_type: 'Villa',
    source: 'Facebook',
    assigned_to: null,
    notes: '',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    tags: [{ id: 't3', name: 'Seller', color: '#10B981' }],
  },
  {
    id: 'c3',
    name: 'Amit Patel',
    phone: '+91 76543 21098',
    stage: 'Site Visit',
    email: 'amit@email.com',
    preferred_location: 'Hinjewadi, Pune',
    budget_min: 7000000,
    budget_max: 12000000,
    property_type: 'Apartment',
    source: 'Instagram',
    assigned_to: 'u2',
    notes: 'Needs parking',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    tags: [{ id: 't2', name: 'Buyer', color: '#3B82F6' }],
  },
  {
    id: 'c4',
    name: 'Sneha Joshi',
    phone: '+91 65432 10987',
    stage: 'Contacted',
    email: '',
    preferred_location: 'Kothrud, Pune',
    budget_min: 4000000,
    budget_max: 6000000,
    property_type: 'Plot',
    source: 'WhatsApp',
    assigned_to: 'u1',
    notes: '',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    tags: [],
  },
];

// ----- Conversations -----
export const MOCK_CONVERSATIONS: any = [
  {
    id: 'conv1',
    contact_id: 'c1',
    contact: MOCK_CONTACTS[0],
    status: 'open',
    unread_count: 3,
    last_message: 'When can we schedule a site visit?',
    last_message_at: new Date(Date.now() - 1800000).toISOString(),
    bot_active: false,
    flow_id: null,
    current_step_index: 0,
    assigned_to: 'u1',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'conv2',
    contact_id: 'c2',
    contact: MOCK_CONTACTS[1],
    status: 'open',
    unread_count: 0,
    last_message: 'Thank you for the information!',
    last_message_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    bot_active: true,
    flow_id: 'flow1',
    current_step_index: 1,
    assigned_to: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'conv3',
    contact_id: 'c3',
    contact: MOCK_CONTACTS[2],
    status: 'open',
    unread_count: 1,
    last_message: 'Can you share the brochure?',
    last_message_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    bot_active: false,
    flow_id: null,
    current_step_index: 0,
    assigned_to: 'u2',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: 'conv4',
    contact_id: 'c4',
    contact: MOCK_CONTACTS[3],
    status: 'resolved',
    unread_count: 0,
    last_message: 'I will get back to you soon.',
    last_message_at: new Date(Date.now() - 86400000).toISOString(),
    bot_active: false,
    flow_id: null,
    current_step_index: 0,
    assigned_to: 'u1',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

// ----- Messages -----
export const MOCK_MESSAGES: any = {
  conv1: [
    {
      id: 'm1',
      conversation_id: 'conv1',
      direction: 'inbound',
      message_type: 'text',
      body: 'Hi, I am interested in 2BHK apartments in Wakad.',
      status: 'read',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      sender: null,
    },
    {
      id: 'm2',
      conversation_id: 'conv1',
      direction: 'outbound',
      message_type: 'text',
      body: 'Hello Rahul! Great to hear from you. We have some excellent properties in Wakad within your budget.',
      status: 'read',
      timestamp: new Date(Date.now() - 7000000).toISOString(),
      sender: { id: 'u1', name: 'Ravi Patil' },
    },
    {
      id: 'm3',
      conversation_id: 'conv1',
      direction: 'inbound',
      message_type: 'text',
      body: 'What is the price range?',
      status: 'read',
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      sender: null,
    },
    {
      id: 'm4',
      conversation_id: 'conv1',
      direction: 'outbound',
      message_type: 'text',
      body: 'We have options from ₹55L to ₹80L. All RERA approved projects.',
      status: 'delivered',
      timestamp: new Date(Date.now() - 3500000).toISOString(),
      sender: { id: 'u1', name: 'Ravi Patil' },
    },
    {
      id: 'm5',
      conversation_id: 'conv1',
      direction: 'inbound',
      message_type: 'text',
      body: 'When can we schedule a site visit?',
      status: 'delivered',
      timestamp: new Date(Date.now() - 1800000).toISOString(),
      sender: null,
    },
  ],
  conv2: [
    {
      id: 'm6',
      conversation_id: 'conv2',
      direction: 'inbound',
      message_type: 'text',
      body: 'Hello, I want to sell my villa in Baner.',
      status: 'read',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      sender: null,
    },
    {
      id: 'm7',
      conversation_id: 'conv2',
      direction: 'outbound',
      message_type: 'template',
      body: 'Hi Priya, Thank you for choosing us to sell your property! We have 10,000+ verified buyers actively looking in Baner.',
      template_name: 'seller_welcome',
      status: 'read',
      timestamp: new Date(Date.now() - 86300000).toISOString(),
      sender: null,
    },
    {
      id: 'm8',
      conversation_id: 'conv2',
      direction: 'inbound',
      message_type: 'text',
      body: 'Thank you for the information!',
      status: 'read',
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      sender: null,
    },
  ],
  conv3: [
    {
      id: 'm9',
      conversation_id: 'conv3',
      direction: 'inbound',
      message_type: 'text',
      body: 'I am looking for 3BHK in Hinjewadi.',
      status: 'read',
      timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
      sender: null,
    },
    {
      id: 'm10',
      conversation_id: 'conv3',
      direction: 'outbound',
      message_type: 'text',
      body: 'Hi Amit! We have great options in Hinjewadi IT Park area.',
      status: 'read',
      timestamp: new Date(Date.now() - 86400000 * 2 + 3600000).toISOString(),
      sender: { id: 'u2', name: 'Neha Kulkarni' },
    },
    {
      id: 'm11',
      conversation_id: 'conv3',
      direction: 'inbound',
      message_type: 'text',
      body: 'Can you share the brochure?',
      status: 'delivered',
      timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
      sender: null,
    },
  ],
  conv4: [
    {
      id: 'm12',
      conversation_id: 'conv4',
      direction: 'inbound',
      message_type: 'text',
      body: 'Looking for a plot in Kothrud.',
      status: 'read',
      timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
      sender: null,
    },
    {
      id: 'm13',
      conversation_id: 'conv4',
      direction: 'outbound',
      message_type: 'text',
      body: 'We have several plot options in Kothrud. Let me share details.',
      status: 'read',
      timestamp: new Date(Date.now() - 86400000 * 3 + 1800000).toISOString(),
      sender: { id: 'u1', name: 'Ravi Patil' },
    },
    {
      id: 'm14',
      conversation_id: 'conv4',
      direction: 'inbound',
      message_type: 'text',
      body: 'I will get back to you soon.',
      status: 'read',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      sender: null,
    },
  ],
};

// ----- Templates -----
export const MOCK_TEMPLATES: any = [
  {
    id: 'tpl1',
    name: 'buyer_welcome',
    category: 'MARKETING',
    language: 'en',
    status: 'APPROVED',
    header_type: 'TEXT',
    header_text: 'Welcome, Property Seeker!',
    body: 'Hi {{1}},\n\nThank you for your interest in buying a property with us!\n\nWe have hundreds of verified properties across {{2}} matching your needs.',
    footer: '',
    buttons: [
      { type: 'QUICK_REPLY', text: 'View Properties' },
      { type: 'QUICK_REPLY', text: 'Talk to Agent' },
    ],
    variables: ['name', 'city'],
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'tpl2',
    name: 'seller_welcome',
    category: 'UTILITY',
    language: 'en',
    status: 'APPROVED',
    header_type: 'TEXT',
    header_text: 'Sell Your Property Fast!',
    body: 'Hi {{1}},\n\nThank you for choosing us to sell your property!\n\nWe have 10,000+ verified buyers actively looking in {{2}}.',
    footer: '',
    buttons: [{ type: 'QUICK_REPLY', text: 'List My Property' }],
    variables: ['name', 'city'],
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'tpl3',
    name: 'site_visit_confirmation',
    category: 'UTILITY',
    language: 'en',
    status: 'PENDING',
    header_type: 'TEXT',
    header_text: 'Site Visit Confirmed!',
    body: 'Hi {{1}},\n\nYour site visit has been confirmed!\n\n🏠 Property: {{2}}\n📅 Date: {{3}}\n⏰ Time: {{4}}',
    footer: 'Reply CANCEL to cancel',
    buttons: [
      { type: 'QUICK_REPLY', text: 'Confirm' },
      { type: 'QUICK_REPLY', text: 'Reschedule' },
    ],
    variables: [],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'tpl4',
    name: 'otp_verification',
    category: 'AUTHENTICATION',
    language: 'en',
    status: 'REJECTED',
    header_type: null,
    header_text: null,
    body: '{{1}} is your verification code for {{2}}.\n\nThis code expires in 10 minutes.',
    footer: null,
    buttons: [],
    variables: [],
    rejection_reason: 'Template does not follow authentication guidelines.',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

// ----- Campaigns -----
export const MOCK_CAMPAIGNS: any = [
  {
    id: 'camp1',
    name: 'Wakad Property Blast - June',
    template_id: 'tpl1',
    template: MOCK_TEMPLATES[0],
    status: 'completed',
    total_contacts: 245,
    sent_count: 245,
    delivered_count: 238,
    read_count: 187,
    failed_count: 7,
    scheduled_at: null,
    filters: { stage: ['New', 'Contacted'] },
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'camp2',
    name: 'Seller Outreach - Baner',
    template_id: 'tpl2',
    template: MOCK_TEMPLATES[1],
    status: 'running',
    total_contacts: 120,
    sent_count: 87,
    delivered_count: 81,
    read_count: 54,
    failed_count: 6,
    scheduled_at: null,
    filters: {},
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'camp3',
    name: 'New Project Launch Q3',
    template_id: 'tpl1',
    template: MOCK_TEMPLATES[0],
    status: 'draft',
    total_contacts: 0,
    sent_count: 0,
    delivered_count: 0,
    read_count: 0,
    failed_count: 0,
    scheduled_at: new Date(Date.now() + 86400000 * 3).toISOString(),
    filters: {},
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
];

// ----- Chatbot Flows -----
export const MOCK_FLOWS: any = [
  {
    id: 'flow1',
    name: 'Welcome Flow',
    description: 'Greets new leads and qualifies them',
    is_active: true,
    is_default: true,
    trigger_keyword: '',
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    steps: [
      {
        id: 'fs1',
        flow_id: 'flow1',
        step_index: 0,
        step_type: 'message',
        message_text: 'Welcome! How can we help you today?',
        buttons: null,
        save_response_as: null,
        tag_id: null,
        assign_to: null,
        stage: null,
        template_id: null,
        next_step_index: null,
        conditions: null,
        created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
      },
      {
        id: 'fs2',
        flow_id: 'flow1',
        step_index: 1,
        step_type: 'question',
        message_text: 'What type of property are you looking for?',
        buttons: null,
        save_response_as: 'notes',
        tag_id: null,
        assign_to: null,
        stage: null,
        template_id: null,
        next_step_index: null,
        conditions: null,
        created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
      },
      {
        id: 'fs3',
        flow_id: 'flow1',
        step_index: 2,
        step_type: 'stage',
        message_text: '',
        buttons: null,
        save_response_as: null,
        tag_id: null,
        assign_to: null,
        stage: 'Contacted',
        template_id: null,
        next_step_index: null,
        conditions: null,
        created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
      },
    ],
  },
  {
    id: 'flow2',
    name: 'Buyer Qualification',
    description: 'Qualifies buyer leads with key questions',
    is_active: true,
    is_default: false,
    trigger_keyword: 'buy',
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    steps: [
      {
        id: 'fs4',
        flow_id: 'flow2',
        step_index: 0,
        step_type: 'message',
        message_text: 'Great! Tell me about your budget.',
        buttons: null,
        save_response_as: null,
        tag_id: null,
        assign_to: null,
        stage: null,
        template_id: null,
        next_step_index: null,
        conditions: null,
        created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
      },
      {
        id: 'fs5',
        flow_id: 'flow2',
        step_index: 1,
        step_type: 'buttons',
        message_text: 'What is your preferred location?',
        buttons: [
          { id: 'b1', title: 'Wakad' },
          { id: 'b2', title: 'Baner' },
          { id: 'b3', title: 'Hinjewadi' },
        ],
        save_response_as: null,
        tag_id: null,
        assign_to: null,
        stage: null,
        template_id: null,
        next_step_index: null,
        conditions: null,
        created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
      },
    ],
  },
  {
    id: 'flow3',
    name: 'Site Visit Follow-up',
    description: '',
    is_active: false,
    is_default: false,
    trigger_keyword: 'visit',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    steps: [],
  },
];

// ----- Users -----
export const MOCK_USERS: any = [
  { id: 'u1', name: 'Ravi Patil', email: 'ravi@company.com', role: 'admin', is_active: true },
  { id: 'u2', name: 'Neha Kulkarni', email: 'neha@company.com', role: 'sales', is_active: true },
  { id: 'u3', name: 'Suresh Deshpande', email: 'suresh@company.com', role: 'pre_sales', is_active: false },
];

// ----- Tags -----
export const MOCK_TAGS: any = [
  { id: 't1', name: 'Hot Lead', color: '#EF4444' },
  { id: 't2', name: 'Buyer', color: '#3B82F6' },
  { id: 't3', name: 'Seller', color: '#10B981' },
  { id: 't4', name: 'Investor', color: '#8B5CF6' },
  { id: 't5', name: 'VIP', color: '#F59E0B' },
];

// ----- Analytics -----
export const MOCK_ANALYTICS:any = {
  total_contacts: 1247,
  new_leads_today: 12,
  new_leads_week: 87,
  open_conversations: 34,
  messages_sent_today: 156,
  messages_received_today: 203,
  response_rate: 77,
  active_campaigns: 2,
};

export const MOCK_MESSAGE_VOLUME :any= [
  { date: 'Apr 14', inbound: 45, outbound: 38 },
  { date: 'Apr 15', inbound: 62, outbound: 51 },
  { date: 'Apr 16', inbound: 38, outbound: 29 },
  { date: 'Apr 17', inbound: 71, outbound: 63 },
  { date: 'Apr 18', inbound: 55, outbound: 44 },
  { date: 'Apr 19', inbound: 89, outbound: 76 },
  { date: 'Apr 20', inbound: 67, outbound: 55 },
];

export const MOCK_CAMPAIGN_STATS:any = [
  { name: 'buyer_welcome', sent: 245, delivered: 238, read: 187, failed: 7 },
  { name: 'seller_welcome', sent: 87, delivered: 81, read: 54, failed: 6 },
];

// ----- Notes (optional, for conversation notes) -----
export const MOCK_NOTES: any = {
  conv1: [
    {
      id: 'note1',
      conversation_id: 'conv1',
      body: 'Customer wants 2BHK in Wakad. Follow up next week.',
      author: MOCK_USERS[0],
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  conv2: [],
  conv3: [],
  conv4: [],
};