import React, { useState } from 'react';
import { X, Download, Share, FileText, Eye, Printer, Mail, MessageCircle, BarChart3, PieChart, TrendingUp } from 'lucide-react';

const PropertyReportModal = ({ isOpen, onClose, property }: any) => {
  const [reportType, setReportType] = useState('comprehensive');
  const [includePhotos, setIncludePhotos] = useState(true);
  const [includeInspection, setIncludeInspection] = useState(true);
  const [includeMaintenance, setIncludeMaintenance] = useState(true);
  const [includeMarketAnalysis, setIncludeMarketAnalysis] = useState(true);

  if (!isOpen) return null;

  const reportTypes = [
    { 
      value: 'comprehensive', 
      label: 'Comprehensive Report', 
      description: 'Complete property analysis with all details',
      pages: '15-20 pages'
    },
    { 
      value: 'inspection', 
      label: 'Inspection Report', 
      description: 'Detailed inspection findings and recommendations',
      pages: '8-12 pages'
    },
    { 
      value: 'maintenance', 
      label: 'Maintenance Report', 
      description: 'Maintenance suggestions and cost estimates',
      pages: '5-8 pages'
    },
    { 
      value: 'market', 
      label: 'Market Analysis', 
      description: 'Market trends and pricing analysis',
      pages: '6-10 pages'
    },
    { 
      value: 'summary', 
      label: 'Executive Summary', 
      description: 'Brief overview for quick review',
      pages: '2-3 pages'
    }
  ];

  const generateReport = () => {
    // Simulate report generation
    const reportData = {
      type: reportType,
      property: property,
      generatedAt: new Date().toISOString(),
      includePhotos,
      includeInspection,
      includeMaintenance,
      includeMarketAnalysis
    };

    console.log('Generating report:', reportData);
    
    // Create a dummy PDF download
    const link = document.createElement('a');
    link.href = 'data:application/pdf;base64,JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PAovVGl0bGUgKFByb3BlcnR5IFJlcG9ydCkKL0NyZWF0b3IgKFJlc2FsZUV4cGVydCkKL1Byb2R1Y2VyIChSZXNhbGVFeHBlcnQpCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9UeXBlIC9DYXRhbG9nCi9QYWdlcyAzIDAgUgo+PgplbmRvYmoKMyAwIG9iago8PAovVHlwZSAvUGFnZXMKL0tpZHMgWzQgMCBSXQovQ291bnQgMQo+PgplbmRvYmoKNCAwIG9iago8PAovVHlwZSAvUGFnZQovUGFyZW50IDMgMCBSCi9NZWRpYUJveCBbMCAwIDYxMiA3OTJdCj4+CmVuZG9iagp4cmVmCjAgNQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMDA3NCAwMDAwMCBuIAowMDAwMDAwMTIxIDAwMDAwIG4gCjAwMDAwMDAxNzggMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSA1Ci9Sb290IDIgMCBSCj4+CnN0YXJ0eHJlZgoyNzMKJSVFT0YK';
    link.download = `${property.title}-${reportType}-report.pdf`;
    link.click();
    
    alert('Report generated and downloaded successfully!');
  };

  const shareReport = (channel: string) => {
    const reportUrl = `https://resaleexpert.com/reports/${property.propertyId}/${reportType}`;
    const message = `Property Report: ${property.title}\n\nComprehensive ${reportType} report is ready for review.\n\nView Report: ${reportUrl}\n\nGenerated by ResaleExpert`;

    switch (channel) {
      case 'whatsapp':
        window.open(`https://wa.me/${property.seller?.phone?.replace(/\D/g, '')}?text=${encodeURIComponent(message)}`, '_blank');
        break;
      case 'email':
        const subject = `Property Report - ${property.title}`;
        window.open(`mailto:${property.seller?.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`, '_blank');
        break;
      default:
        navigator.clipboard.writeText(reportUrl);
        alert('Report link copied to clipboard!');
    }
  };

  const formatCurrency = (amount: number) => {
    if (amount >= 10000000) return `₹${(amount / 10000000).toFixed(1)}Cr`;
    if (amount >= 100000) return `₹${(amount / 100000).toFixed(1)}L`;
    return `₹${amount.toLocaleString('en-IN')}`;
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden">
        {/* Header */}
        <div className="p-6 border-b border-gray-200 bg-gradient-to-r from-purple-50 to-indigo-50">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Generate Property Report</h2>
              <p className="text-gray-600 mt-1">{property.title}</p>
            </div>
            <button
              onClick={onClose}
              className="p-2 rounded-xl bg-white hover:bg-gray-50 transition-colors shadow-lg"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        <div className="p-6 max-h-[70vh] overflow-y-auto">
          {/* Property Summary */}
          <div className="bg-gray-50 rounded-xl p-4 mb-6">
            <h3 className="font-semibold text-gray-900 mb-3">Property Summary</h3>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 text-sm">
              <div>
                <span className="text-gray-500">Property:</span>
                <span className="font-semibold ml-2">{property.title}</span>
              </div>
              <div>
                <span className="text-gray-500">Location:</span>
                <span className="font-semibold ml-2">{property.location}, {property.city}</span>
              </div>
              <div>
                <span className="text-gray-500">Type:</span>
                <span className="font-semibold ml-2">{property.unitType} • {property.carpetArea} sq ft</span>
              </div>
              <div>
                <span className="text-gray-500">Price:</span>
                <span className="font-semibold ml-2">{formatCurrency(property.budget)}</span>
              </div>
            </div>
          </div>

          {/* Report Type Selection */}
          <div className="mb-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Select Report Type</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {reportTypes.map((type) => (
                <button
                  key={type.value}
                  onClick={() => setReportType(type.value)}
                  className={`p-4 rounded-xl border-2 transition-all text-left ${
                    reportType === type.value
                      ? 'border-purple-500 bg-purple-50'
                      : 'border-gray-200 hover:border-gray-300'
                  }`}
                >
                  <div className="font-medium text-gray-900">{type.label}</div>
                  <div className="text-sm text-gray-600 mt-1">{type.description}</div>
                  <div className="text-xs text-purple-600 mt-2">{type.pages}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Report Options */}
          <div className="mb-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Report Options</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <label className="flex items-center space-x-3 p-3 border border-gray-200 rounded-lg hover:bg-gray-50">
                <input
                  type="checkbox"
                  checked={includePhotos}
                  onChange={(e) => setIncludePhotos(e.target.checked)}
                  className="rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <div>
                  <div className="font-medium text-gray-900">Include Photos</div>
                  <div className="text-sm text-gray-600">Property images and visual documentation</div>
                </div>
              </label>
              
              <label className="flex items-center space-x-3 p-3 border border-gray-200 rounded-lg hover:bg-gray-50">
                <input
                  type="checkbox"
                  checked={includeInspection}
                  onChange={(e) => setIncludeInspection(e.target.checked)}
                  className="rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <div>
                  <div className="font-medium text-gray-900">Include Inspection Data</div>
                  <div className="text-sm text-gray-600">Detailed inspection findings and ratings</div>
                </div>
              </label>
              
              <label className="flex items-center space-x-3 p-3 border border-gray-200 rounded-lg hover:bg-gray-50">
                <input
                  type="checkbox"
                  checked={includeMaintenance}
                  onChange={(e) => setIncludeMaintenance(e.target.checked)}
                  className="rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <div>
                  <div className="font-medium text-gray-900">Include Maintenance Suggestions</div>
                  <div className="text-sm text-gray-600">Repair recommendations and cost estimates</div>
                </div>
              </label>
              
              <label className="flex items-center space-x-3 p-3 border border-gray-200 rounded-lg hover:bg-gray-50">
                <input
                  type="checkbox"
                  checked={includeMarketAnalysis}
                  onChange={(e) => setIncludeMarketAnalysis(e.target.checked)}
                  className="rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                />
                <div>
                  <div className="font-medium text-gray-900">Include Market Analysis</div>
                  <div className="text-sm text-gray-600">Market trends and pricing insights</div>
                </div>
              </label>
            </div>
          </div>

          {/* Report Preview */}
          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h3 className="text-lg font-semibold text-gray-900 mb-4">Report Preview</h3>
            <div className="bg-gray-50 rounded-lg p-4 h-64 overflow-auto">
              <div className="space-y-4">
                <div className="text-center border-b pb-4">
                  <h1 className="text-xl font-bold text-gray-900">{reportTypes.find(t => t.value === reportType)?.label}</h1>
                  <p className="text-gray-600">{property.title}</p>
                  <p className="text-sm text-gray-500">Generated on {new Date().toLocaleDateString()}</p>
                </div>
                
                <div className="space-y-3">
                  <div>
                    <h2 className="font-semibold text-gray-900">Property Overview</h2>
                    <p className="text-sm text-gray-700">
                      {property.unitType} property located in {property.location}, {property.city} with {property.carpetArea} sq ft area.
                      Current asking price: {formatCurrency(property.budget)}.
                    </p>
                  </div>
                  
                  {includeInspection && (
                    <div>
                      <h2 className="font-semibold text-gray-900">Inspection Summary</h2>
                      <p className="text-sm text-gray-700">
                        Overall property rating: {property.inspectionReport?.overallRating || 8}/10.
                        Property is in good condition with minor maintenance requirements.
                      </p>
                    </div>
                  )}
                  
                  {includeMaintenance && (
                    <div>
                      <h2 className="font-semibold text-gray-900">Maintenance Recommendations</h2>
                      <p className="text-sm text-gray-700">
                        Estimated maintenance cost: ₹{(property.maintenanceReport?.totalEstimatedCost || 50000).toLocaleString('en-IN')}.
                        Timeline: {property.maintenanceReport?.timelineWeeks || 4} weeks.
                      </p>
                    </div>
                  )}
                  
                  {includeMarketAnalysis && (
                    <div>
                      <h2 className="font-semibold text-gray-900">Market Analysis</h2>
                      <p className="text-sm text-gray-700">
                        Current market rate: ₹18,500/sq ft. Property is priced competitively with 5.2% above market average.
                        Expected appreciation: 8-12% annually.
                      </p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-200 bg-gray-50">
          <div className="flex items-center justify-between">
            <div className="text-sm text-gray-500">
              Report will be generated in PDF format
            </div>
            <div className="flex items-center space-x-3">
              <button
                onClick={() => shareReport('whatsapp')}
                className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
              >
                <MessageCircle size={16} />
                <span>Share via WhatsApp</span>
              </button>
              <button
                onClick={() => shareReport('email')}
                className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                <Mail size={16} />
                <span>Share via Email</span>
              </button>
              <button
                onClick={generateReport}
                className="flex items-center space-x-2 px-6 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
              >
                <Download size={16} />
                <span>Generate & Download</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PropertyReportModal;